import streamlit as st
st.title("Internet Search + Math AI Assistant")
prompt = st.text_input("Enter any question here:")

from langchain.llms import OpenAI # Brings in the OpenAI API

llm = OpenAI(openai_api_key='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')# innitializes the llm(the ai), so it's ready for use

if prompt:
    response = llm(prompt=prompt) #When someone enters the prompt, a responce is generated by the AI, which is then displayed in the website
    st.write(response)